//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhmCalcMaui.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WhmCalcMaui.Resources.Localization.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string btn_no {
            get {
                return ResourceManager.GetString("btn_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string btn_yes {
            get {
                return ResourceManager.GetString("btn_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AntiX.
        /// </summary>
        internal static string mod_anti_x {
            get {
                return ResourceManager.GetString("mod_anti_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devastating Wounds.
        /// </summary>
        internal static string mod_devastating_wounds {
            get {
                return ResourceManager.GetString("mod_devastating_wounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feel No Pain.
        /// </summary>
        internal static string mod_feel_no_pain {
            get {
                return ResourceManager.GetString("mod_feel_no_pain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half Damage.
        /// </summary>
        internal static string mod_half_damage {
            get {
                return ResourceManager.GetString("mod_half_damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invulnerable Save.
        /// </summary>
        internal static string mod_invul_save {
            get {
                return ResourceManager.GetString("mod_invul_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lethal Hits.
        /// </summary>
        internal static string mod_lethal_hits {
            get {
                return ResourceManager.GetString("mod_lethal_hits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minus 1 to Damage.
        /// </summary>
        internal static string mod_minus_1_damage {
            get {
                return ResourceManager.GetString("mod_minus_1_damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minus 1 to Wound.
        /// </summary>
        internal static string mod_minus_1_to_wound {
            get {
                return ResourceManager.GetString("mod_minus_1_to_wound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plus 1 to Wound.
        /// </summary>
        internal static string mod_plus_1_to_wound {
            get {
                return ResourceManager.GetString("mod_plus_1_to_wound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Roll 1s to Hit.
        /// </summary>
        internal static string mod_reroll_1s_to_hit {
            get {
                return ResourceManager.GetString("mod_reroll_1s_to_hit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Roll 1s to Wound.
        /// </summary>
        internal static string mod_reroll_1s_to_wound {
            get {
                return ResourceManager.GetString("mod_reroll_1s_to_wound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Roll to Hit.
        /// </summary>
        internal static string mod_reroll_all_to_hit {
            get {
                return ResourceManager.GetString("mod_reroll_all_to_hit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Roll to Wound.
        /// </summary>
        internal static string mod_reroll_all_to_wound {
            get {
                return ResourceManager.GetString("mod_reroll_all_to_wound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sustained Hits.
        /// </summary>
        internal static string mod_sustained_hits {
            get {
                return ResourceManager.GetString("mod_sustained_hits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to delete this target?.
        /// </summary>
        internal static string popup_confirm_targetdelete {
            get {
                return ResourceManager.GetString("popup_confirm_targetdelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target with that name already exist. Do you wish to update its properties?.
        /// </summary>
        internal static string popup_confirm_targetupdate {
            get {
                return ResourceManager.GetString("popup_confirm_targetupdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add target..
        /// </summary>
        internal static string popup_error_couldnotadd {
            get {
                return ResourceManager.GetString("popup_error_couldnotadd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete target..
        /// </summary>
        internal static string popup_error_couldnotdelete {
            get {
                return ResourceManager.GetString("popup_error_couldnotdelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update target..
        /// </summary>
        internal static string popup_error_couldnotupdate {
            get {
                return ResourceManager.GetString("popup_error_couldnotupdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target added to Database..
        /// </summary>
        internal static string popup_message_targetadded {
            get {
                return ResourceManager.GetString("popup_message_targetadded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target has been deleted..
        /// </summary>
        internal static string popup_message_targetremoved {
            get {
                return ResourceManager.GetString("popup_message_targetremoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target has been updated..
        /// </summary>
        internal static string popup_message_targetupdated {
            get {
                return ResourceManager.GetString("popup_message_targetupdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string popup_type_confirmation {
            get {
                return ResourceManager.GetString("popup_type_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string popup_type_error {
            get {
                return ResourceManager.GetString("popup_type_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string popup_type_success {
            get {
                return ResourceManager.GetString("popup_type_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string popup_type_warning {
            get {
                return ResourceManager.GetString("popup_type_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArmorPen.
        /// </summary>
        internal static string textbox_armorpen {
            get {
                return ResourceManager.GetString("textbox_armorpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attacks.
        /// </summary>
        internal static string textbox_attacks {
            get {
                return ResourceManager.GetString("textbox_attacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        internal static string textbox_damage {
            get {
                return ResourceManager.GetString("textbox_damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dead Models.
        /// </summary>
        internal static string textbox_deadmodels {
            get {
                return ResourceManager.GetString("textbox_deadmodels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dev Wounds.
        /// </summary>
        internal static string textbox_devwounds {
            get {
                return ResourceManager.GetString("textbox_devwounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hits.
        /// </summary>
        internal static string textbox_hits {
            get {
                return ResourceManager.GetString("textbox_hits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lethals.
        /// </summary>
        internal static string textbox_lethalhits {
            get {
                return ResourceManager.GetString("textbox_lethalhits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string textbox_save {
            get {
                return ResourceManager.GetString("textbox_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength.
        /// </summary>
        internal static string textbox_strength {
            get {
                return ResourceManager.GetString("textbox_strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sus Hits.
        /// </summary>
        internal static string textbox_sushits {
            get {
                return ResourceManager.GetString("textbox_sushits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Damage.
        /// </summary>
        internal static string textbox_totaldamage {
            get {
                return ResourceManager.GetString("textbox_totaldamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toughness.
        /// </summary>
        internal static string textbox_toughness {
            get {
                return ResourceManager.GetString("textbox_toughness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnSaved.
        /// </summary>
        internal static string textbox_unsavedwonds {
            get {
                return ResourceManager.GetString("textbox_unsavedwonds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill.
        /// </summary>
        internal static string textbox_weaponskill {
            get {
                return ResourceManager.GetString("textbox_weaponskill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wounds.
        /// </summary>
        internal static string textbox_wounds {
            get {
                return ResourceManager.GetString("textbox_wounds", resourceCulture);
            }
        }
    }
}
